/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyHospitalRouteImport } from './routes/verify-hospital'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardPrescriptionsIndexRouteImport } from './routes/dashboard/prescriptions/index'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard/patients/index'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/dashboard/appointments/index'
import { Route as DashboardStaffIdRouteImport } from './routes/dashboard/staff/$id'
import { Route as DashboardPrescriptionsCreateRouteImport } from './routes/dashboard/prescriptions/create'
import { Route as DashboardPrescriptionsIdRouteImport } from './routes/dashboard/prescriptions/$id'
import { Route as DashboardPatientsRegisterRouteImport } from './routes/dashboard/patients/register'
import { Route as DashboardPatientsOpdQueueRouteImport } from './routes/dashboard/patients/opd-queue'
import { Route as DashboardPatientsIdRouteImport } from './routes/dashboard/patients/$id'
import { Route as DashboardAppointmentsScheduleRouteImport } from './routes/dashboard/appointments/schedule'
import { Route as DashboardAppointmentsIdRouteImport } from './routes/dashboard/appointments/$id'
import { Route as DashboardPrescriptionsTemplatesIndexRouteImport } from './routes/dashboard/prescriptions/templates/index'
import { Route as DashboardPrescriptionsTemplatesCreateRouteImport } from './routes/dashboard/prescriptions/templates/create'
import { Route as DashboardPrescriptionsTemplatesIdRouteImport } from './routes/dashboard/prescriptions/templates/$id'

const VerifyHospitalRoute = VerifyHospitalRouteImport.update({
  id: '/verify-hospital',
  path: '/verify-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsIndexRoute =
  DashboardPrescriptionsIndexRouteImport.update({
    id: '/prescriptions/',
    path: '/prescriptions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffIdRoute = DashboardStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsCreateRoute =
  DashboardPrescriptionsCreateRouteImport.update({
    id: '/prescriptions/create',
    path: '/prescriptions/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsIdRoute =
  DashboardPrescriptionsIdRouteImport.update({
    id: '/prescriptions/$id',
    path: '/prescriptions/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsRegisterRoute =
  DashboardPatientsRegisterRouteImport.update({
    id: '/patients/register',
    path: '/patients/register',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsOpdQueueRoute =
  DashboardPatientsOpdQueueRouteImport.update({
    id: '/patients/opd-queue',
    path: '/patients/opd-queue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIdRoute = DashboardPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsScheduleRoute =
  DashboardAppointmentsScheduleRouteImport.update({
    id: '/appointments/schedule',
    path: '/appointments/schedule',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsIdRoute = DashboardAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsTemplatesIndexRoute =
  DashboardPrescriptionsTemplatesIndexRouteImport.update({
    id: '/prescriptions/templates/',
    path: '/prescriptions/templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsTemplatesCreateRoute =
  DashboardPrescriptionsTemplatesCreateRouteImport.update({
    id: '/prescriptions/templates/create',
    path: '/prescriptions/templates/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPrescriptionsTemplatesIdRoute =
  DashboardPrescriptionsTemplatesIdRouteImport.update({
    id: '/prescriptions/templates/$id',
    path: '/prescriptions/templates/$id',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/prescriptions/templates': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-hospital': typeof VerifyHospitalRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/schedule': typeof DashboardAppointmentsScheduleRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/opd-queue': typeof DashboardPatientsOpdQueueRoute
  '/dashboard/patients/register': typeof DashboardPatientsRegisterRoute
  '/dashboard/prescriptions/$id': typeof DashboardPrescriptionsIdRoute
  '/dashboard/prescriptions/create': typeof DashboardPrescriptionsCreateRoute
  '/dashboard/staff/$id': typeof DashboardStaffIdRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/dashboard/prescriptions/': typeof DashboardPrescriptionsIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/prescriptions/templates/$id': typeof DashboardPrescriptionsTemplatesIdRoute
  '/dashboard/prescriptions/templates/create': typeof DashboardPrescriptionsTemplatesCreateRoute
  '/dashboard/prescriptions/templates/': typeof DashboardPrescriptionsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/staff/$id'
    | '/dashboard/appointments'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/staff'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/prescriptions/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/staff/$id'
    | '/dashboard/appointments'
    | '/dashboard/patients'
    | '/dashboard/prescriptions'
    | '/dashboard/staff'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/prescriptions/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register-hospital'
    | '/reset-password'
    | '/success'
    | '/verify-hospital'
    | '/dashboard/'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/schedule'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/opd-queue'
    | '/dashboard/patients/register'
    | '/dashboard/prescriptions/$id'
    | '/dashboard/prescriptions/create'
    | '/dashboard/staff/$id'
    | '/dashboard/appointments/'
    | '/dashboard/patients/'
    | '/dashboard/prescriptions/'
    | '/dashboard/staff/'
    | '/dashboard/prescriptions/templates/$id'
    | '/dashboard/prescriptions/templates/create'
    | '/dashboard/prescriptions/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  VerifyHospitalRoute: typeof VerifyHospitalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-hospital': {
      id: '/verify-hospital'
      path: '/verify-hospital'
      fullPath: '/verify-hospital'
      preLoaderRoute: typeof VerifyHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/': {
      id: '/dashboard/prescriptions/'
      path: '/prescriptions'
      fullPath: '/dashboard/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/': {
      id: '/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/$id': {
      id: '/dashboard/staff/$id'
      path: '/staff/$id'
      fullPath: '/dashboard/staff/$id'
      preLoaderRoute: typeof DashboardStaffIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/create': {
      id: '/dashboard/prescriptions/create'
      path: '/prescriptions/create'
      fullPath: '/dashboard/prescriptions/create'
      preLoaderRoute: typeof DashboardPrescriptionsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/$id': {
      id: '/dashboard/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/dashboard/prescriptions/$id'
      preLoaderRoute: typeof DashboardPrescriptionsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/register': {
      id: '/dashboard/patients/register'
      path: '/patients/register'
      fullPath: '/dashboard/patients/register'
      preLoaderRoute: typeof DashboardPatientsRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/opd-queue': {
      id: '/dashboard/patients/opd-queue'
      path: '/patients/opd-queue'
      fullPath: '/dashboard/patients/opd-queue'
      preLoaderRoute: typeof DashboardPatientsOpdQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/$id': {
      id: '/dashboard/patients/$id'
      path: '/patients/$id'
      fullPath: '/dashboard/patients/$id'
      preLoaderRoute: typeof DashboardPatientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/schedule': {
      id: '/dashboard/appointments/schedule'
      path: '/appointments/schedule'
      fullPath: '/dashboard/appointments/schedule'
      preLoaderRoute: typeof DashboardAppointmentsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments/$id': {
      id: '/dashboard/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/dashboard/appointments/$id'
      preLoaderRoute: typeof DashboardAppointmentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/templates/': {
      id: '/dashboard/prescriptions/templates/'
      path: '/prescriptions/templates'
      fullPath: '/dashboard/prescriptions/templates'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/templates/create': {
      id: '/dashboard/prescriptions/templates/create'
      path: '/prescriptions/templates/create'
      fullPath: '/dashboard/prescriptions/templates/create'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions/templates/$id': {
      id: '/dashboard/prescriptions/templates/$id'
      path: '/prescriptions/templates/$id'
      fullPath: '/dashboard/prescriptions/templates/$id'
      preLoaderRoute: typeof DashboardPrescriptionsTemplatesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppointmentsIdRoute: typeof DashboardAppointmentsIdRoute
  DashboardAppointmentsScheduleRoute: typeof DashboardAppointmentsScheduleRoute
  DashboardPatientsIdRoute: typeof DashboardPatientsIdRoute
  DashboardPatientsOpdQueueRoute: typeof DashboardPatientsOpdQueueRoute
  DashboardPatientsRegisterRoute: typeof DashboardPatientsRegisterRoute
  DashboardPrescriptionsIdRoute: typeof DashboardPrescriptionsIdRoute
  DashboardPrescriptionsCreateRoute: typeof DashboardPrescriptionsCreateRoute
  DashboardStaffIdRoute: typeof DashboardStaffIdRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
  DashboardPrescriptionsIndexRoute: typeof DashboardPrescriptionsIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardPrescriptionsTemplatesIdRoute: typeof DashboardPrescriptionsTemplatesIdRoute
  DashboardPrescriptionsTemplatesCreateRoute: typeof DashboardPrescriptionsTemplatesCreateRoute
  DashboardPrescriptionsTemplatesIndexRoute: typeof DashboardPrescriptionsTemplatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppointmentsIdRoute: DashboardAppointmentsIdRoute,
  DashboardAppointmentsScheduleRoute: DashboardAppointmentsScheduleRoute,
  DashboardPatientsIdRoute: DashboardPatientsIdRoute,
  DashboardPatientsOpdQueueRoute: DashboardPatientsOpdQueueRoute,
  DashboardPatientsRegisterRoute: DashboardPatientsRegisterRoute,
  DashboardPrescriptionsIdRoute: DashboardPrescriptionsIdRoute,
  DashboardPrescriptionsCreateRoute: DashboardPrescriptionsCreateRoute,
  DashboardStaffIdRoute: DashboardStaffIdRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
  DashboardPrescriptionsIndexRoute: DashboardPrescriptionsIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardPrescriptionsTemplatesIdRoute:
    DashboardPrescriptionsTemplatesIdRoute,
  DashboardPrescriptionsTemplatesCreateRoute:
    DashboardPrescriptionsTemplatesCreateRoute,
  DashboardPrescriptionsTemplatesIndexRoute:
    DashboardPrescriptionsTemplatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  VerifyHospitalRoute: VerifyHospitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
